# Generated by Django 5.1.7 on 2025-03-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="反馈者邮箱"
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("BUG", "Bug报告"),
                            ("Feedback", "功能建议"),
                            ("Question", "内容问题"),
                            ("Payment", "支付问题"),
                            ("OTHER", "其他"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="反馈类型",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("IOS", "iOS"),
                            ("ANDROID", "Android"),
                            ("WEB", "Web"),
                            ("OTHER", "其他"),
                        ],
                        default="IOS",
                        max_length=20,
                        verbose_name="平台",
                    ),
                ),
                ("app_id", models.CharField(max_length=100, verbose_name="应用ID")),
                ("content", models.TextField(verbose_name="反馈内容")),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="是否已处理"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户反馈",
                "verbose_name_plural": "用户反馈",
                "ordering": ["-created_at"],
            },
        ),
    ]
