version: '3.8'

services:
  web:
    build: .
    container_name: usercenter_web
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=UserCenter.settings
      - DJANGO_ENV=development
      - PYTHONPATH=/app
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}  # 连接到宿主机上的PostgreSQL
      - DB_PORT=${DB_PORT}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@${DB_HOST}:6379/0  # 连接到宿主机上的Redis
      - REDIS_PASSWORD==${REDIS_PASSWORD}
    volumes:
      - /var/www/static:/app/staticfiles
      - usercenter_media_volume:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "${APP_PORT:-8000}:8000"  # 应用端口，可通过环境变量配置
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 确保容器可以访问宿主机

volumes:
  usercenter_media_volume:
    name: usercenter_media_volume