# Generated by Django 3.2.25 on 2025-03-12 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='优惠码')),
                ('app_id', models.CharField(default='default', help_text='用于区分不同的应用', max_length=100, verbose_name='应用ID')),
                ('days', models.IntegerField(default=30, help_text='兑换后获得的会员天数', verbose_name='会员天数')),
                ('max_uses', models.IntegerField(default=1, help_text='优惠码可以使用的最大次数', verbose_name='最大使用次数')),
                ('used_count', models.IntegerField(default=0, help_text='优惠码已被使用的次数', verbose_name='已使用次数')),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已过期'), ('used_up', '已用完'), ('disabled', '已禁用')], default='active', max_length=10, verbose_name='状态')),
                ('expires_at', models.DateTimeField(blank=True, help_text='优惠码的过期时间', null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_codes', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '优惠码',
                'verbose_name_plural': '优惠码',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MagicCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='使用时间')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='magics.magiccode', verbose_name='优惠码')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_usages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '优惠码使用记录',
                'verbose_name_plural': '优惠码使用记录',
                'unique_together': {('code', 'user')},
            },
        ),
    ]
