# Generated by Django 3.2.25 on 2025-03-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthprovider',
            name='app_id',
            field=models.CharField(default='default', help_text='用于区分不同的应用', max_length=100, verbose_name='应用ID'),
        ),
        migrations.AddField(
            model_name='oauthprovider',
            name='key_id',
            field=models.CharField(blank=True, help_text='苹果密钥ID', max_length=100, verbose_name='密钥ID'),
        ),
        migrations.AddField(
            model_name='oauthprovider',
            name='private_key',
            field=models.TextField(blank=True, help_text='苹果登录私钥内容', verbose_name='私钥'),
        ),
        migrations.AddField(
            model_name='oauthprovider',
            name='private_key_path',
            field=models.FileField(blank=True, help_text='苹果登录私钥文件', null=True, upload_to='apple_keys/', verbose_name='私钥文件'),
        ),
        migrations.AddField(
            model_name='oauthprovider',
            name='team_id',
            field=models.CharField(blank=True, help_text='苹果开发者团队ID', max_length=100, verbose_name='团队ID'),
        ),
        migrations.AlterField(
            model_name='oauthprovider',
            name='name',
            field=models.CharField(choices=[('wechat', '微信'), ('qq', 'QQ'), ('weibo', '微博'), ('alipay', '支付宝'), ('dingtalk', '钉钉'), ('apple', '苹果'), ('google', '谷歌'), ('facebook', '脸书'), ('twitter', '推特'), ('github', 'GitHub'), ('linkedin', '领英')], max_length=20, verbose_name='名称'),
        ),
        migrations.AlterUniqueTogether(
            name='oauthprovider',
            unique_together={('name', 'app_id')},
        ),
    ]
