# Generated by Django 3.2.25 on 2025-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20250304_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='是否付费用户'),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='付费到期时间'),
        ),
    ]
