# Generated by Django 5.1.7 on 2025-04-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20250311_2157"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_anonymous_user",
            field=models.BooleanField(default=False, verbose_name="是否为匿名用户"),
        ),
    ]
